### ISSUE TITLE
where are the svg font files?

### ISSUE THREAD

**Issue by ort111** [coolbutuseless/hershey#1]
hershey_svg: a list of SVG paths for every glyph.

I don't see these in the repo, maybe I am missing them somehow?  Thanks in advance.

**Comment by coolbutuseless** [comment]
The SVG paths are included as character vectors in the `hershey_svg` object.

e.g. This is what an SVG `<path>` spec looks like: `M0-12L0 2M0 7L-1 8L0 9L1 8L0 7`

See here for more info on SVG paths: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths


```
> hershey_svg$cursive[1:3]
                               1                                2                                3 
                          "M0 0" "M0-12L0 2M0 7L-1 8L0 9L1 8L0 7"           "M-4-12L-4-5M4-12L4-5" 
```
